### ISSUE TITLE
Feature: FileListBlock CSS classes and list type

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya-generic#16]
I think it would be nice to have the possibility to:

- add CSS classes for the file list block (list, list item and link element)
- have a switch between unordered and ordered lists

What do you think? I can make a PR if it is ok.

**Comment by nadar** [comment]
Sure, sounds good. Here you can see an example for ul/li setup: https://github.com/luyadev/luya-generic/blob/master/src/blocks/ListBlock.php#L54
